server:
  port: 8081

spring:
  application:
    name: notification-rate-limiter-service
  data:
    redis:
      host: localhost
      port: 6379
  datasource:
    url: jdbc:h2:mem:corp_xyz_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: none # We will use Flyway for schema
  h2:
    console:
      enabled: true
      path: /h2-console
  flyway:
    enabled: true
    locations: classpath:db/migration # Flyway script location

notification-rate-limiter-service:
  global-bucket:
     key: "rate_limit:global_system"
     capacity: 1000
     duration-in-minutes: 1


#logging:
#  level:
#    org.springframework.boot.autoconfigure.flyway: debug